### ISSUE TITLE
Update for Docusaurus 2.3.0

### ISSUE THREAD

**Issue by Noou-Ben** [typesense/docusaurus-theme-search-typesense#27]
The current version of the plugin (V0.8.0) will not install due to dependency conflicts.

```
[master_ncfgzwhuqm]:docs$ npm install docusaurus-theme-search-typesense@next --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: docs@0.0.0
npm ERR! Found: @docusaurus/core@2.3.0
npm ERR! node_modules/@docusaurus/core
npm ERR!   @docusaurus/core@"2.3.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @docusaurus/core@"2.2.0" from docusaurus-theme-search-typesense@0.8.0-0
npm ERR! node_modules/docusaurus-theme-search-typesense
npm ERR!   docusaurus-theme-search-typesense@"0.8.0-0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/master/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/master/.npm/_logs/2023-01-28T20_49_31_015Z-debug-0.log
```

**Comment by jasonbosco** [comment]
Could you upgrade to `0.9.0-0` of `docusaurus-theme-search-typesense` and see if that fixes this issue?

**Comment by dtlhlbs** [comment]
On `yarn build` I'm getting `TypeError: Cannot read properties of undefined (reading 'searchPagePath')` with an upgrade to Docusaurus 2.3.0 and  `docusaurus-theme-search-typesense@0.9.0-0`

**Comment by slorber** [comment]
@jasonbosco please do not use `useSearchPage` and preferably no internal theme-common api. We can refactor those at any time in minor releases and break your plugin.

The amount of code here is quite small and simple, and you'd rather copy it in your own project instead.

See also https://github.com/facebook/docusaurus/issues/8623#issuecomment-1415753285

**Comment by jasonbosco** [comment]
Posted an update here: https://github.com/facebook/docusaurus/issues/8623#issuecomment-1416535241

Thank you for the pointers @slorber!

**Comment by jasonbosco** [comment]
Could you upgrade to `0.9.0-2` of docusaurus-theme-search-typesense and `2.3.1` of docusaurus and see if that fixes this issue?

I just tried it on my [test ground](https://github.com/typesense/docusaurus-typesense-testground) and it seems to work fine for me...

**Comment by joostdecock** [comment]
@jasonbosco I can confirm that upgrading to `0.9.0-2` fixes the issue. Thanks for your swift response 🙏 👍

**Comment by jasonbosco** [comment]
Great! Thank you for confirming. 

I've published `0.9.0`.

**Comment by dtlhlbs** [comment]
Just fyi I am still getting this error with `docusaurus@2.3.1` and `docusaurus-theme-search-typesense@0.9.0-0`. I am NOT getting this error with `docusaurus-theme-search-typesense@0.9.0-2`.

**Comment by jasonbosco** [comment]
@dtlhlbs `0.9.0-0` is an earlier pre-release version. You want to use `0.9.0`.

**Comment by Noou-Ben** [comment]
> Could you upgrade to `0.9.0-2` of docusaurus-theme-search-typesense and `2.3.1` of docusaurus and see if that fixes this issue?
> 
> I just tried it on my [test ground](https://github.com/typesense/docusaurus-typesense-testground) and it seems to work fine for me...

Can confirm this worked for me 👍

**Comment by dtlhlbs** [comment]
doh! 🤦 confirmed `0.9.0` is working, thanks!
